version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "this is the buildspec in the root dir"
      - ls $CODEBUILD_SRC_DIR
      - ls $CODEBUILD_SRC_DIR/deploy
      - pip install awscli --upgrade
  build:
    commands:
      - echo "Hello, World!"
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
