version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - echo "This is the deploy buildspec"
      - pip install awscli --upgrade
  build:
    commands:
      - echo "Hello, World!"
  post_build:
    commands:
artifacts:
  files:
    - '**/*'
